---
title: "p8105_hw6_yz4990"
author: "Yucheng Zhao"
date: "2024-12-02"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


## Problem 1.
```{r}

```



## Problem 2.
data cleaning
```{r}
homi_df = read_csv("./data/homicide-data.csv", 
                   na = c("NA", "Unknown", ""), 
                   ) |> 
  janitor::clean_names() |> 
  mutate(
    city_state = paste(city, state, sep = ", "),
    resolved = as.numeric(disposition == "Closed by arrest")
    ) |> 
  filter(city != "Dallas", 
         city != "Phoenix",
         city != "Kansas City", 
         city != "Tulsa") |> 
  filter(victim_race == "White" | victim_race == "Black") |> 
  drop_na(victim_age) |> 
  mutate(victim_age = as.numeric(victim_age))

head(homi_df)
```

logistic regression for binary variable "resolved"
```{r}
balti_df = homi_df |> 
  filter(city == "Baltimore")

fit_logistic = 
  balti_df |> 
  glm(resolved ~ victim_age + victim_sex + victim_race, data = _, family = binomial()) 

fit_logistic |> 
  broom::tidy(conf.int = TRUE) |> 
  filter(term == "victim_sexMale") |> 
  mutate(OR = exp(estimate)) |>
  select(term, OR, conf.low, conf.high) |> 
  knitr::kable(digits = 3)
```


glm for each city
```{r}
results_df = homi_df |> 
  group_by(city) |> 
  nest() |> 
  mutate(
    model = purrr::map(data, \(x) glm(resolved ~ victim_age + victim_sex + victim_race, 
                                          data = x, family = binomial())),
    outputs = purrr::map(model, \(x) broom::tidy(x, conf.int = TRUE))
    ) |> 
  unnest(outputs) |> 
  filter(term == "victim_sexMale") |> 
  mutate(
    OR = exp(estimate),
    conf.low = exp(conf.low),
    conf.high = exp(conf.high)
    ) |>
  select(term, OR, conf.low, conf.high)
  
knitr::kable(results_df, digits = 3)
```


plot of the estimated ORs and CIs for each city
```{r}
ggplot(results_df, aes(x = reorder(city, OR), y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(
    title = "Estimated Odds Ratios with Confidence Intervals by City",
    x = "City",
    y = "Odds Ratio"
  ) + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90)
  )
  
```


## Problem 3.
```{r}

```




```{r}

```




```{r}

```




```{r}

```




```{r}

```




```{r}

```




```{r}

```




```{r}

```





